server:
  port: 8085

spring:
  application:
    name: config
  profiles:
    active: api
  config:
#    import: optional:configserver:http://localhost:8087
    import: optional:configserver:http://192.168.50.53:8087

  #로컬 DB 설정
#  datasource:
#    url: jdbc:mariadb://localhost:3306/project3
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: root
#    password: 6639

#VM DB설정
#  datasource:
#    url: jdbc:mariadb://192.168.50.15:3306/project3
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: root
#    password: alsrl123

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

#파일 업로드관련 용량 설정
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB
      enabled: true

#rabbitMQ 설정
  rabbitmq:
    host: 100.0.0.157
    port: 25672
    username: minki
    password: 1234

# config client에서 Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: busrefresh
#        include: "*"
