server:
    port: 8083

spring:
    application:
        name: config
    profiles:
        active: app
    config:
#        import: optional:configserver:http://localhost:8087
#            import: optional:configserver:192.168.50.53:8087
        import: optional:configserver:http://192.168.50.53:8087


    #rabbitMQ 설정
    rabbitmq:
        host: 100.0.0.157
        port: 25672
        username: minki
        password: 1234

    servlet:
        multipart:
            maxFileSize: 10MB
            maxRequestSize: 20MB
            enabled: true

# config client에서 Actuator 설정
management:
    endpoints:
        web:
            exposure:
                include: busrefresh
#        include: "*"

